# -*- coding: utf-8 -*-
"""
DO NOT EDIT THIS FILE!
It is automatically generated from opcfoundation.org schemas.
Model Uri:http://opcfoundation.org/UA/
Version:1.05.05
Publication date:2025-06-30T00:00:00Z

File creation Date:2025-11-13 08:18:23.331459+00:00
"""
import datetime
from dateutil.tz import tzutc
from asyncua import ua
from asyncua.ua import NodeId, QualifiedName, NumericNodeId, StringNodeId, GuidNodeId
from asyncua.ua import NodeClass, LocalizedText




def create_standard_address_space_Services_25(server):

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15285, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(692, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15285, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15286, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(695, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15286, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15287, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(698, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15287, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15288, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(701, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15288, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15289, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(704, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15289, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15290, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(707, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15290, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15291, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(710, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15291, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15292, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(713, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15292, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15293, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(719, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15293, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15294, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(722, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15294, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15295, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(725, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15295, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15304, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(948, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15304, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15312, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(728, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15312, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15313, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(731, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15313, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15314, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(734, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15314, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15315, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(737, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15315, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15320, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(740, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15320, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15321, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(743, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15321, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15322, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(746, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15322, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15323, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(749, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15323, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15324, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(752, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15324, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15325, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(755, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15325, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15326, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(758, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15326, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15327, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(761, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15327, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15328, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(764, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15328, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15329, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(767, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15329, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15331, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(770, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15331, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15332, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(773, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15332, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15333, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(776, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15333, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15335, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(779, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15335, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15336, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(782, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15336, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15337, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(785, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15337, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15338, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(788, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15338, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15339, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(791, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15339, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15340, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(794, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15340, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15341, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(797, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15341, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15342, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(800, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15342, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15343, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(803, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15343, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15344, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(945, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15344, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15345, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(809, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15345, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15346, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(806, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15346, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15347, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(914, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15347, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15348, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(917, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15348, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15349, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(920, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15349, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15350, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(818, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15350, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15351, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(821, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15351, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15352, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(824, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15352, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15353, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(827, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15353, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15354, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(830, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15354, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15355, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(833, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15355, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15356, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(836, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15356, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15357, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(839, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15357, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15358, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(842, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15358, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15359, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(845, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15359, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15360, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(848, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15360, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15361, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(338, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15361, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15362, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(853, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15362, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15363, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(11943, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15363, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15364, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(11944, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15364, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15365, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(856, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15365, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15366, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(859, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15366, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15367, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(862, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15367, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15368, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(865, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15368, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15369, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(868, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15369, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15370, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(871, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15370, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15371, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(299, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15371, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15372, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(874, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15372, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15373, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(877, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15373, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15374, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(897, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15374, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15375, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(884, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15375, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15376, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(887, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15376, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15377, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(12171, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15377, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15378, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(12172, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15378, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15379, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(12079, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15379, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15380, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(12080, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15380, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15381, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(894, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15381, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(24042, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(24033, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(24042, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)

    refs = []
    ref = ua.AddReferencesItem(
        IsForward=False,
        ReferenceTypeId=NumericNodeId(38, 0),
        SourceNodeId=NumericNodeId(15382, 0),
        TargetNodeClass=NodeClass.DataType,
        TargetNodeId=NumericNodeId(891, 0),
        )
    refs.append(ref)
    ref = ua.AddReferencesItem(
        IsForward=True,
        ReferenceTypeId=NumericNodeId(40, 0),
        SourceNodeId=NumericNodeId(15382, 0),
        TargetNodeClass=NodeClass.ObjectType,
        TargetNodeId=NumericNodeId(76, 0),
        )
    refs.append(ref)
    server.add_references(refs)
