from __future__ import annotations

from typing import Protocol


class ClientObserver(Protocol):
    def on_request(self, request_type: str, duration: float, error: BaseException | None) -> None: ...

    def on_state_change(self, state: str) -> None: ...

    def on_subscription_event(self, event: str, subscription_id: int | None) -> None: ...

    def on_notification(self, subscription_id: int | None, item_count: int) -> None: ...
