#!/usr/bin/env python

import sys
from pathlib import Path

sys.path.append(f'{Path(__file__).parent.parent}')

from asyncua.tools import uahistoryread


if __name__ == "__main__":
    uahistoryread()
