#!/usr/bin/env python3

import logging
import sys
from pathlib import Path

logging.basicConfig(level=logging.DEBUG)
sys.path.append(f'{Path(__file__).parent.parent}')

from asyncua.tools import uaserver

if __name__ == "__main__":
    uaserver()
